# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-18 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.CharField(choices=[('tech', 'Technical'), ('product', 'Product'), ('shop', 'Shop')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
